image: node:20-alpine

stages:
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
